camera_frame: realsense_color_optical_frame

camera_info_topic: /realsense/color/camera_info
rgb_topic: /realsense/color/image_raw
depth_topic: /realsense/aligned_depth_to_color/image_raw

est_refine_iter : 5
objects:
  gray_block:  /home/mrrobot/Theises/dope_assets/models/gray_block/GrayBlock.obj
  blue_block:  /home/mrrobot/Theises/dope_assets/models/gray_block/GrayBlock.obj
